/*
File Name: 
    21-find-the-difference/Solution.cs
FileType: 
    Visual C# Source file
Author:
    https://github.com/brian-reeder
Created On:
    July 23, 2022, 14:32:40

Description:
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more
    letter at a random position.

    Return the letter that was added to t.
*/
namespace Dictionaries {
    public class Solution {
        public char FindTheDifference(string s, string t) {

            // Initialize lookup tables
            var sHash = new Dictionary<char, int>((Int32)'z' - (Int32)'a');
            var tHash = new Dictionary<char, int>(((Int32)'z' - (Int32)'a'));
            for(char k = 'a'; k <= 'z'; k++) {
                sHash[k] = 0;
                tHash[k] = 0;
            }

            // Load lookup tables.
            int i;
            for(i = 0; i < s.Length; i++) {
                sHash[s[i]]++;
                tHash[t[i]]++;
            }

            tHash[t[i]]++;
            for(char k = 'a'; k <= 'z'; k++)
                if(sHash[k] != tHash[k])
                    return k;

            return '\0';
        }
    }
}

namespace Sorter {
    public class Solution{
        public char FindTheDifference(string s, string t) {
            var sSorted = s.ToArray();
            Array.Sort(sSorted);

            var tSorted = t.ToArray();
            Array.Sort(tSorted);


            int i;
            for(i = 0; i < s.Length; i++)
                if(sSorted[i] != tSorted[i])
                    break;

            return tSorted[i];
        }
    }
}